# Generated by Django 2.1.4 on 2019-01-02 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('expedido', models.IntegerField(choices=[(1, 'ORURO'), (2, 'LA PAZ'), (3, 'COCHABAMBA'), (4, 'SANTA CRUZ'), (5, 'CHUQUISACA'), (6, 'POTOSI'), (7, 'TARIJA'), (8, 'BENI'), (9, 'PANDO')], default=1)),
                ('nro_documento', models.CharField(max_length=50)),
                ('estado_civil', models.IntegerField(choices=[(1, 'SOLTERO(A)'), (2, 'CASADO(A)'), (3, 'VIUDO(A)'), (4, 'DIVORCIADO(A)')], default=1)),
                ('genero', models.IntegerField(choices=[(1, 'MASCULINO'), (2, 'FEMENINO')], default=1)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
