# Generated by Django 2.1.5 on 2019-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='natural',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.IntegerField(choices=[(0, 'NATURAL'), (1, 'JURIDICO(O)')], default=0),
        ),
    ]
