# Generated by Django 2.1.5 on 2019-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20190130_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fundempresa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='nit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='poder',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='razon_social',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona',
            field=models.IntegerField(choices=[(0, 'NATURAL'), (1, 'JURIDICO(A)')], default=0),
        ),
    ]
