# Generated by Django 2.1.5 on 2019-01-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20190130_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=50),
        ),
    ]
