# Generated by Django 2.2.4 on 2019-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_personaback'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaback',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
