# Generated by Django 2.1.4 on 2019-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20190130_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_mat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_pat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
