# Generated by Django 2.1.4 on 2019-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20190206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fundempresa',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='poder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
