# Generated by Django 2.1.5 on 2019-02-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20190227_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='natural',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nro_documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
