# Generated by Django 2.1.5 on 2019-02-27 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20190227_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_documento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
