# Generated by Django 2.1.5 on 2019-02-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_persona_fecha_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha_documento',
        ),
    ]
