# Generated by Django 2.1.4 on 2019-06-19 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerotramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.IntegerField(choices=[(1, 'CERTIFICACION FIRMAS Y RUBRICAS'), (2, 'AUTORIZACION DE VIAJE DE MENOR')], default=1)),
                ('numero', models.IntegerField(default=0)),
                ('gestion', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('fecha_documento', models.DateField(default=datetime.datetime.now)),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('hora_registro', models.TimeField(default=datetime.datetime.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pagina_inicio', models.IntegerField(blank=True, default=0)),
                ('pagina_fin', models.IntegerField(blank=True, default=0)),
                ('estado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramitepersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.BooleanField(default=True)),
                ('testigo', models.BooleanField(default=False)),
                ('tipo', models.IntegerField(default=0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.Tramite')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tramiteviaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_nacimiento', models.CharField(blank=True, max_length=50)),
                ('destino', models.CharField(blank=True, max_length=250)),
                ('motivo_viaje', models.CharField(blank=True, max_length=250)),
                ('residencia_viaje', models.CharField(blank=True, max_length=250)),
                ('tiempo_ausencia', models.IntegerField(default=0)),
                ('fecha_retorno', models.DateField(default=datetime.datetime.now)),
                ('objeto_viaje', models.CharField(blank=True, max_length=250)),
                ('tipo', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.Tramite')),
            ],
        ),
    ]
