# Generated by Django 2.1.4 on 2019-01-02 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.IntegerField(choices=[(1, 'CERTIFICACION RUBRICAS'), (2, 'OTRO TRAMITE')])),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('titulo_aux', models.CharField(blank=True, max_length=250)),
                ('formularios', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('hora_registro', models.TimeField(default=django.utils.timezone.now)),
                ('fecha_Actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
