# Generated by Django 2.1.4 on 2019-06-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='pagina_fin',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='pagina_inicio',
        ),
        migrations.AddField(
            model_name='tramite',
            name='formularios',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
