# Generated by Django 2.1.4 on 2019-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_auto_20190206_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.IntegerField(choices=[(1, 'CERTIFICACION FIRMAS Y RUBRICAS')], default=1),
        ),
    ]
