# Generated by Django 2.1.4 on 2019-02-13 23:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20190206_1229'),
        ('tramite', '0004_auto_20190206_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramitePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.IntegerField(default=0)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to='persona.Persona')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite', to='tramite.Tramite')),
            ],
        ),
    ]
