# Generated by Django 2.1.4 on 2019-06-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_auto_20190620_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='contra_parte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='parte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='formularios',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
