# Generated by Django 2.1.4 on 2019-02-18 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_tramitepersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitepersona',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='tramitepersona',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.Tramite'),
        ),
    ]
