# Generated by Django 2.1.4 on 2019-06-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_auto_20190625_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitepersona',
            name='contra_parte',
            field=models.BooleanField(default=True),
        ),
    ]
