# Generated by Django 2.1.4 on 2019-02-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_auto_20190218_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numerotramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('gestion', models.IntegerField()),
                ('tipo', models.IntegerField()),
            ],
        ),
    ]
