# Generated by Django 2.1.4 on 2019-06-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_tramitepersona_contra_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='parte_aux',
            field=models.TextField(blank=True),
        ),
    ]
