# Generated by Django 2.1.4 on 2019-02-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_numerotramite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitepersona',
            name='pagina_fin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='tramitepersona',
            name='pagina_incio',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
