# Generated by Django 2.1.4 on 2019-06-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_auto_20190627_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='parte_aux',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
