# Generated by Django 2.1.4 on 2019-02-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_auto_20190222_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitepersona',
            name='pagina_fin',
        ),
        migrations.RemoveField(
            model_name='tramitepersona',
            name='pagina_incio',
        ),
        migrations.AddField(
            model_name='tramite',
            name='pagina_fin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramite',
            name='pagina_inicio',
            field=models.IntegerField(default=0),
        ),
    ]
