# Generated by Django 2.1.4 on 2019-06-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0009_auto_20190628_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='estado',
        ),
    ]
