# Generated by Django 2.1.4 on 2019-02-22 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0009_auto_20190222_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
