# Generated by Django 2.1.4 on 2019-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_remove_tramite_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
