# Generated by Django 2.1.4 on 2019-02-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0010_auto_20190222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='gestion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
