# Generated by Django 2.1.4 on 2019-07-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0011_tramite_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteviaje',
            name='acompanante',
            field=models.BooleanField(default=False),
        ),
    ]
