# Generated by Django 2.1.4 on 2019-02-26 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0012_auto_20190225_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
