# Generated by Django 2.1.4 on 2019-07-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0012_tramiteviaje_acompanante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteviaje',
            name='firma',
            field=models.BooleanField(default=True),
        ),
    ]
