# Generated by Django 2.2.4 on 2019-08-19 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0014_tramiteviaje_lugar_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramiteback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('tipo_tramite', models.IntegerField(choices=[(1, 'CERTIFICACION FIRMAS Y RUBRICAS'), (2, 'AUTORIZACION DE VIAJE DE MENOR')], default=1)),
                ('numero', models.IntegerField(default=0)),
                ('gestion', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('fecha_documento', models.DateField(default=datetime.datetime.now)),
                ('fecha_registro', models.DateField(default=datetime.datetime.now)),
                ('hora_registro', models.TimeField(default=datetime.datetime.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('formularios', models.CharField(blank=True, max_length=250)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
