# Generated by Django 2.1.4 on 2019-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0014_auto_20190226_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramitepersona',
            name='testigo',
            field=models.BooleanField(default=False),
        ),
    ]
