# Generated by Django 2.2.4 on 2019-08-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0015_tramiteback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramitepersonaback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('tramite', models.IntegerField(default=0)),
                ('persona', models.IntegerField(default=0)),
                ('firma', models.BooleanField(default=True)),
                ('testigo', models.BooleanField(default=False)),
                ('tipo', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
