# Generated by Django 2.1.5 on 2019-02-27 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0015_tramitepersona_testigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_documento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
