# Generated by Django 2.2.4 on 2019-08-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0016_tramitepersonaback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.IntegerField(choices=[(1, 'CERTIFICACION FIRMAS Y RUBRICAS')], default=1),
        ),
    ]
