# Generated by Django 2.1.5 on 2019-02-27 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0016_tramite_fecha_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='fecha_documento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
