# Generated by Django 2.2.4 on 2019-08-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0017_auto_20190828_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramiteback',
            name='contra_parte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tramiteback',
            name='contra_parte_imp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tramiteback',
            name='parte',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tramiteback',
            name='parte_aux',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tramiteback',
            name='parte_imp',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tramitepersonaback',
            name='contra_parte',
            field=models.BooleanField(default=True),
        ),
    ]
