# Generated by Django 2.1.4 on 2019-04-04 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0018_auto_20190404_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramiteviaje',
            old_name='cn',
            new_name='certificado_nacimiento',
        ),
        migrations.RenameField(
            model_name='tramiteviaje',
            old_name='residencia',
            new_name='destino',
        ),
        migrations.RemoveField(
            model_name='tramitepersona',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='fecha_retorno',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='motivo_viaje',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='objeto_viaje',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='residencia_viaje',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='tiempo_ausencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramiteviaje',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
