# Generated by Django 2.1.4 on 2019-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0019_auto_20190404_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramiteviaje',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
    ]
